import type { LegalResource } from "@/types/resources";

export const fallbackResources: LegalResource[] = [
  {
    id: "lanc-raleigh",
    name: "Legal Aid of North Carolina - Raleigh Office",
    type: "clinic",
    state: "NC",
    city: "Raleigh",
    phone: "866-219-5262",
    website: "https://legalaidnc.org/",
    coverage: "Statewide intake and local office support",
    categories: ["Housing", "Employment", "Family", "Consumer", "General"],
    source: "curated",
  },
  {
    id: "lanc-charlotte",
    name: "Legal Aid of North Carolina - Charlotte Office",
    type: "clinic",
    state: "NC",
    city: "Charlotte",
    phone: "866-219-5262",
    website: "https://legalaidnc.org/offices/",
    coverage: "Mecklenburg and nearby counties",
    categories: ["Housing", "Employment", "Family", "Consumer", "General"],
    source: "curated",
  },
  {
    id: "pisgah-legal",
    name: "Pisgah Legal Services",
    type: "clinic",
    state: "NC",
    city: "Asheville",
    phone: "828-253-0406",
    website: "https://www.pisgahlegal.org/",
    coverage: "Western North Carolina",
    categories: ["Housing", "Family", "Consumer", "General"],
    source: "curated",
  },
  {
    id: "ncbar-referral",
    name: "North Carolina Bar Association - Lawyer Referral Service",
    type: "lawyer-referral",
    state: "NC",
    city: "Raleigh",
    phone: "800-662-7660",
    website: "https://www.ncbar.org/public-resources/find-an-nc-lawyer/",
    coverage: "North Carolina statewide referral",
    categories: ["Housing", "Employment", "Family", "Consumer", "Immigration", "General"],
    source: "curated",
  },
  {
    id: "lawhelpnc",
    name: "LawHelpNC Legal Help Directory",
    type: "lawyer-referral",
    state: "NC",
    website: "https://www.lawhelpnc.org/find-legal-help/directory",
    coverage: "North Carolina county and topic directory",
    categories: ["Housing", "Employment", "Family", "Consumer", "Immigration", "General"],
    source: "curated",
  },
  {
    id: "lsc-national",
    name: "Legal Services Corporation - National Legal Aid Finder",
    type: "lawyer-referral",
    state: "US",
    website: "https://www.lsc.gov/about-lsc/what-legal-aid/i-need-legal-help",
    coverage: "US nationwide address-based lookup",
    categories: ["Housing", "Employment", "Family", "Consumer", "Immigration", "General"],
    source: "curated",
  },
];
